services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - godowns
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - godowns
    env_file:
      - ./server/.env

networks:
  godowns:
    driver: bridge